name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run lint
      - run: npx tsc --noEmit

  build:
    needs: lint-and-typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run db:generate
        env:
          DATABASE_URL: "file:./dev.db"
      - run: bun run build
        env:
          NEXTAUTH_SECRET: "ci-test-secret-min-32-chars-long!"
          DATABASE_URL: "file:./dev.db"